/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.math.BigDecimal;
import javax.swing.JOptionPane;
import model.Cliente;
import model.Fornecedor;
import model.Produto;
import repository.ClienteRep;
import repository.FornecedorRep;
import repository.ProdutoRep;
import interfaces.ClienteInterface;
import interfaces.FornecedorInterface;
import interfaces.ProdutoInterface;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Victor
 */
public class TelaCadastrosEAlteracoes extends javax.swing.JFrame {

    private ClienteInterface vi = new ClienteInterface();
    private FornecedorInterface foce = new FornecedorInterface();
    private ProdutoInterface pod = new ProdutoInterface();

    /**
     * Creates new form TelaAddProduto
     */
    public TelaCadastrosEAlteracoes() {
        initComponents();
        centralizar();
        invisivel();
        refreshClientesTable();
        refreshFornecedoresTable();
        refreshProdutosTable();

    }

    public void centralizar() {

        setLocationRelativeTo(null);

    }

    private void refreshClientesTable() {
        ClienteRep lis = new ClienteRep();
        vi = new ClienteInterface(lis.listar());
        tblCliente.setModel(vi);

    }

    private void refreshFornecedoresTable() {
        FornecedorRep lis = new FornecedorRep();
        foce = new FornecedorInterface(lis.listar());
        tblFornecedor.setModel(foce);
    }

    private void refreshProdutosTable() {
        ProdutoRep lis = new ProdutoRep();
        pod = new ProdutoInterface(lis.listar());
        tblProduto.setModel(pod);
    }

    public void invisivel() {
        //Oculta os paineis
        pnFornecedores.setVisible(false);
        pnClientes.setVisible(false);
        pnProdutos.setVisible(false);

        btnConfirmCadastrar.setVisible(false);

        btnAlterar.setVisible(false);
        btnDeletar.setVisible(false);

        rBtnCliente.setVisible(false);
        rBtnFornecedor.setVisible(false);
        rBtnProduto.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rBtnCliente = new javax.swing.JRadioButton();
        rBtnFornecedor = new javax.swing.JRadioButton();
        rBtnProduto = new javax.swing.JRadioButton();
        pnProdutos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        txtPV = new javax.swing.JTextField();
        txtPC = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtNomeProduto = new javax.swing.JTextField();
        txtIdProdutos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnFornecedores = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblFornecedor = new javax.swing.JTable();
        txtCnpj = new javax.swing.JTextField();
        txtNomeFornecedor = new javax.swing.JTextField();
        txtTelefon_a = new javax.swing.JTextField();
        txtTelefone_b = new javax.swing.JTextField();
        pnClientes = new javax.swing.JPanel();
        txtCPFCliente = new javax.swing.JTextField();
        txtNomeCliente = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        txtIdClientes = new javax.swing.JTextField();
        btnAlterar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnConfirmCadastrar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Times New Roman", 1, 24))); // NOI18N
        jPanel1.setMaximumSize(new java.awt.Dimension(720, 390));
        jPanel1.setMinimumSize(new java.awt.Dimension(720, 390));
        jPanel1.setPreferredSize(new java.awt.Dimension(720, 390));

        buttonGroup1.add(rBtnCliente);
        rBtnCliente.setText("Cliente");
        rBtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnClienteActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBtnFornecedor);
        rBtnFornecedor.setText("Fornecedor");
        rBtnFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnFornecedorActionPerformed(evt);
            }
        });

        buttonGroup1.add(rBtnProduto);
        rBtnProduto.setText("Produto");
        rBtnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnProdutoActionPerformed(evt);
            }
        });

        pnProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblProduto);

        txtNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeProdutoActionPerformed(evt);
            }
        });

        jLabel1.setText("Cod Fornecedor");

        jLabel2.setText("Nome do Produto");

        jLabel3.setText("Qtde Estoque");

        jLabel4.setText("Preço Custo");

        jLabel5.setText("Preço Venda");

        javax.swing.GroupLayout pnProdutosLayout = new javax.swing.GroupLayout(pnProdutos);
        pnProdutos.setLayout(pnProdutosLayout);
        pnProdutosLayout.setHorizontalGroup(
            pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtIdProdutos))
                .addGap(18, 18, 18)
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNomeProduto))
                .addGap(18, 18, 18)
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtQuantidade))
                .addGap(18, 18, 18)
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPC))
                .addGap(18, 18, 18)
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPV))
                .addGap(7, 244, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProdutosLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );
        pnProdutosLayout.setVerticalGroup(
            pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProdutosLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnProdutosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtNomeProduto, txtPC, txtPV, txtQuantidade});

        pnFornecedores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fornecedores", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        tblFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblFornecedor.setUpdateSelectionOnSort(false);
        tblFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFornecedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblFornecedor);

        txtTelefon_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefon_aActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnFornecedoresLayout = new javax.swing.GroupLayout(pnFornecedores);
        pnFornecedores.setLayout(pnFornecedoresLayout);
        pnFornecedoresLayout.setHorizontalGroup(
            pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTelefon_a, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtTelefone_b, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnFornecedoresLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pnFornecedoresLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCnpj, txtNomeFornecedor});

        pnFornecedoresLayout.setVerticalGroup(
            pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFornecedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefon_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18))); // NOI18N

        txtNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeClienteActionPerformed(evt);
            }
        });

        tblCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClienteMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblCliente);

        javax.swing.GroupLayout pnClientesLayout = new javax.swing.GroupLayout(pnClientes);
        pnClientes.setLayout(pnClientesLayout);
        pnClientesLayout.setHorizontalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtIdClientes)
                .addGap(18, 18, 18)
                .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtCPFCliente)
                .addGap(336, 336, 336))
        );
        pnClientesLayout.setVerticalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnClientesLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pnClientesLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCPFCliente, txtNomeCliente});

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/shuffle.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/voltar.png"))); // NOI18N
        btnCancelar.setText("Voltar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConfirmCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save-disk.png"))); // NOI18N
        btnConfirmCadastrar.setText("Cadastrar");
        btnConfirmCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmCadastrarActionPerformed(evt);
            }
        });

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/actualize-arrows-couple-in-circle.png"))); // NOI18N
        btnCadastrar.setText("Novo");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Alterar Existente");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConfirmCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeletar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAlterar))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rBtnCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBtnFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rBtnProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addGap(152, 152, 152))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnAtualizar, btnCadastrar, btnCancelar, btnConfirmCadastrar, btnDeletar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(rBtnProduto)
                    .addComponent(rBtnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnFornecedor)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAtualizar)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmCadastrar)
                    .addComponent(btnDeletar)
                    .addComponent(btnAlterar))
                .addGap(18, 18, 18)
                .addComponent(pnProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnCadastrar, btnCancelar, btnConfirmCadastrar, btnDeletar});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        invisivel();

        rBtnCliente.setVisible(true);
        rBtnFornecedor.setVisible(true);
        rBtnProduto.setVisible(true);

        buttonGroup1.clearSelection();

        btnAlterar.setVisible(true);
        btnDeletar.setVisible(true);
        btnCancelar.setVisible(true);
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        invisivel();
        buttonGroup1.clearSelection();

        rBtnCliente.setVisible(true);
        rBtnFornecedor.setVisible(true);
        rBtnProduto.setVisible(true);

        btnCancelar.setVisible(true);
        btnConfirmCadastrar.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnConfirmCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmCadastrarActionPerformed

        if (rBtnCliente.isSelected()) {
            Cliente cli = new Cliente();
            
            cli.setNomeCliente(txtNomeCliente.getText());
            cli.setCpf(txtCPFCliente.getText());

            ClienteRep crep = new ClienteRep();
            crep.salvar(cli);

            JOptionPane.showMessageDialog(null, txtNomeCliente.getText() + " Cliente cadastrado com sucesso!");
            refreshClientesTable();

            txtCPFCliente.setText("");
            txtNomeCliente.setText("");

        } else if (rBtnProduto.isSelected()) {
            

            Produto produto = new Produto();

            produto.setNomeProduto(txtNomeProduto.getText());
            produto.setQtdEstoque(Integer.parseInt(txtQuantidade.getText()));
            produto.setPrecoCusto(BigDecimal.valueOf(Double.parseDouble(txtPC.getText())));
            produto.setPrecoVenda(BigDecimal.valueOf(Double.parseDouble(txtPV.getText())));
            produto.setFornecedor(produto.getFornecedor());

            ProdutoRep addProduto = new ProdutoRep();
            addProduto.salvar(produto);

            JOptionPane.showMessageDialog(null, txtNomeProduto.getText() + " Produto cadastrado com sucesso!");
            refreshProdutosTable();

        } else if (rBtnFornecedor.isSelected()) {
            
            Fornecedor fornecedor = new Fornecedor();

            fornecedor.setNomeFornecedor(txtNomeFornecedor.getText());
            fornecedor.setCnpj(txtCnpj.getText());
            fornecedor.setTelefone_a(txtTelefon_a.getText());
            fornecedor.setTelefone_b(txtTelefone_b.getText());

            FornecedorRep fornecedorRep = new FornecedorRep();
            fornecedorRep.salvar(fornecedor);

            JOptionPane.showMessageDialog(null, txtNomeCliente.getText() + " Cliente cadastrado com sucesso!");
            refreshFornecedoresTable();
        }
    }//GEN-LAST:event_btnConfirmCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed

        if (rBtnCliente.isSelected()) {

            ClienteRep deletarCliente = new ClienteRep();
            deletarCliente.excluir(deletarCliente.buscarPorID(Integer.parseInt(txtIdClientes.getText())));

            refreshClientesTable();
            JOptionPane.showMessageDialog(null, txtNomeCliente.getText() + " Cliente Deletado!");

            txtCPFCliente.setText("");
            txtNomeCliente.setText("");

        } else if (rBtnFornecedor.isSelected()) {

            Fornecedor fornecedor = new Fornecedor();

            FornecedorRep deletarFornecedor = new FornecedorRep();
            deletarFornecedor.excluir(fornecedor);

            refreshFornecedoresTable();
            JOptionPane.showMessageDialog(null, txtNomeFornecedor.getText() + " Fornecedor Deletado!");

        } else if (rBtnProduto.isSelected()) {
            ProdutoRep deletarProduto = new ProdutoRep();
            deletarProduto.excluir(deletarProduto.buscarPorID(Integer.parseInt(txtIdProdutos.getText())));

            refreshProdutosTable();
            JOptionPane.showMessageDialog(null, txtNomeProduto.getText() + " Produto Deletado!");

        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        if (rBtnCliente.isSelected()) {
            Cliente cli = new Cliente();
            cli.setIdCliente(Integer.parseInt(txtIdClientes.getText()));
            cli.setNomeCliente(txtNomeCliente.getText());
            cli.setCpf(txtCPFCliente.getText());
            ClienteRep crep = new ClienteRep();
            crep.salvar(cli);

            JOptionPane.showMessageDialog(null, txtNomeCliente.getText() + " Alterado com sucesso!");

        }
        if (rBtnProduto.isSelected()) {
            

            Produto produto = new Produto();
            produto.setIdproduto(Integer.parseInt(txtIdProdutos.getText()));
            produto.setNomeProduto(txtNomeProduto.getText());
            produto.setQtdEstoque(Integer.parseInt(txtQuantidade.getText()));
            produto.setPrecoCusto(BigDecimal.valueOf(Double.parseDouble(txtPC.getText())));
            produto.setPrecoVenda(BigDecimal.valueOf(Double.parseDouble(txtPV.getText())));
            produto.setFornecedor(produto.getFornecedor());

            ProdutoRep addProduto = new ProdutoRep();
            addProduto.salvar(produto);

            JOptionPane.showMessageDialog(null, txtNomeProduto.getText() + " Alterado com sucesso!");

        }
        if (rBtnFornecedor.isSelected()) {
            
            Fornecedor fornecedor = new Fornecedor();

            fornecedor.setNomeFornecedor(txtNomeFornecedor.getText());
            fornecedor.setCnpj(txtCnpj.getText());
            fornecedor.setTelefone_a(txtTelefon_a.getText());
            fornecedor.setTelefone_b(txtTelefone_b.getText());

            FornecedorRep fornecedorRep = new FornecedorRep();
            fornecedorRep.salvar(fornecedor);

            JOptionPane.showMessageDialog(null, txtNomeFornecedor.getText() + " Alterado com sucesso!");

        }
        refreshClientesTable();
        refreshFornecedoresTable();
        refreshProdutosTable();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void rBtnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnProdutoActionPerformed
        if (rBtnProduto.isSelected()) {
            pnFornecedores.setVisible(false);

            pnClientes.setVisible(false);
            pnProdutos.setVisible(true);

        }

    }//GEN-LAST:event_rBtnProdutoActionPerformed

    private void rBtnFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnFornecedorActionPerformed
        if (rBtnFornecedor.isSelected()) {
            pnFornecedores.setVisible(true);

            pnClientes.setVisible(false);
            pnProdutos.setVisible(false);

        }

    }//GEN-LAST:event_rBtnFornecedorActionPerformed

    private void rBtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnClienteActionPerformed

        if (rBtnCliente.isSelected()) {
            pnClientes.setVisible(true);

            pnFornecedores.setVisible(false);
            pnProdutos.setVisible(false);

        }

    }//GEN-LAST:event_rBtnClienteActionPerformed

    private void tblProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutoMouseClicked
        int linha = tblProduto.getSelectedRow();
        txtIdProdutos.setText(tblProduto.getValueAt(linha, 0).toString());
        txtNomeProduto.setText(tblProduto.getValueAt(linha, 1).toString());
        txtQuantidade.setText(tblProduto.getValueAt(linha, 2).toString());
        txtPC.setText(tblProduto.getValueAt(linha, 3).toString());
        txtPV.setText(tblProduto.getValueAt(linha, 4).toString());

    }//GEN-LAST:event_tblProdutoMouseClicked

    private void tblClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClienteMouseClicked
        int linha = tblCliente.getSelectedRow();
        txtIdClientes.setText(tblCliente.getValueAt(linha, 0).toString());
        txtNomeCliente.setText(tblCliente.getValueAt(linha, 1).toString());
        txtCPFCliente.setText(tblCliente.getValueAt(linha, 2).toString());

    }//GEN-LAST:event_tblClienteMouseClicked

    private void tblFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFornecedorMouseClicked
        int linha = tblFornecedor.getSelectedRow();

        txtNomeFornecedor.setText(tblFornecedor.getValueAt(linha, 1).toString());
        txtCnpj.setText(tblFornecedor.getValueAt(linha, 2).toString());
    }//GEN-LAST:event_tblFornecedorMouseClicked

    private void txtNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeClienteActionPerformed

    private void txtNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeProdutoActionPerformed

    private void txtTelefon_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefon_aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefon_aActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrosEAlteracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrosEAlteracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrosEAlteracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastrosEAlteracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastrosEAlteracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConfirmCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnClientes;
    private javax.swing.JPanel pnFornecedores;
    private javax.swing.JPanel pnProdutos;
    private javax.swing.JRadioButton rBtnCliente;
    private javax.swing.JRadioButton rBtnFornecedor;
    private javax.swing.JRadioButton rBtnProduto;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblFornecedor;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTextField txtCPFCliente;
    private javax.swing.JTextField txtCnpj;
    private javax.swing.JTextField txtIdClientes;
    private javax.swing.JTextField txtIdProdutos;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeFornecedor;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPC;
    private javax.swing.JTextField txtPV;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtTelefon_a;
    private javax.swing.JTextField txtTelefone_b;
    // End of variables declaration//GEN-END:variables
}
